/**
 * Terminal — xterm.js terminal connected to the server PTY via WebSocket.
 *
 * Design constraints:
 *   - xterm instance is created ONCE per sessionId and never recreated on reconnect.
 *     This preserves scrollback history across connection drops.
 *   - onData (keyboard → PTY) is registered ONCE on xterm, held in a ref.
 *     The ref always points at the current live WebSocket so we never leak listeners.
 *   - WebSocket is torn down and rebuilt on reconnect without touching xterm.
 *   - key={sessionId} on this component in App.jsx guarantees a full remount
 *     when switching sessions, so there is no cross-session state bleed.
 *
 * WebSocket protocol:
 *   Client → Server: { type: 'input', data } | { type: 'resize', cols, rows }
 *   Server → Client: { type: 'output', data } | { type: 'exit', exitCode }
 */

import { useEffect, useRef, useState, useCallback } from 'react'
import { Terminal as XTerm } from '@xterm/xterm'
import { FitAddon } from '@xterm/addon-fit'
import { WebLinksAddon } from '@xterm/addon-web-links'
import '@xterm/xterm/css/xterm.css'

const WS_BASE = `${window.location.protocol === 'https:' ? 'wss' : 'ws'}://${window.location.host}`

const XTERM_THEME = {
  background:    '#020507',
  foreground:    '#b0c8e0',
  cursor:        '#00ffa3',
  cursorAccent:  '#020507',
  selectionBackground: 'rgba(0,255,163,0.15)',
  black:         '#0d1117',  brightBlack:   '#3d5470',
  red:           '#ff4d6a',  brightRed:     '#ff7088',
  green:         '#00ffa3',  brightGreen:   '#4dffc4',
  yellow:        '#f5c542',  brightYellow:  '#ffd766',
  blue:          '#4d9fff',  brightBlue:    '#80baff',
  magenta:       '#9d6fff',  brightMagenta: '#bf9fff',
  cyan:          '#00d4e8',  brightCyan:    '#40e8f8',
  white:         '#b0c8e0',  brightWhite:   '#e2e8f0',
}

const RECONNECT_DELAYS = [500, 1000, 2000, 4000, 8000]

/**
 * Wrapper around fitAddon.fit() that preserves the user's scroll position.
 *
 * xterm.js's resize path (triggered by fit()) modifies the internal `ydisp`
 * offset as it reflows buffer content, then syncs the DOM scrollTop to match.
 * This can yank the viewport to the top of the scrollback when the user has
 * scrolled up to read earlier output.
 *
 * Strategy: save the user's offset-from-bottom before fit(), then restore it.
 * If the user was already at the bottom (following live output), explicitly
 * re-anchor after fit() — xterm's internal reflow can lose the bottom position
 * when column changes cause baseY to shift unpredictably.
 */
function safeFit(term, fitAddon) {
  const buf = term.buffer.active
  const viewportY = buf.viewportY
  const baseY     = buf.baseY
  const wasAtBottom = (viewportY >= baseY)

  try { fitAddon.fit() } catch { return }

  if (wasAtBottom) {
    term.scrollToBottom()
  } else {
    const offsetFromBottom = baseY - viewportY
    const newBaseY = term.buffer.active.baseY
    const target = Math.max(0, newBaseY - offsetFromBottom)
    term.scrollToLine(target)
  }
}

/**
 * Matches programmatic escape-sequence responses generated by xterm.js itself
 * (as opposed to genuine user keyboard input).  These responses flow through
 * the same onData callback as keystrokes but must NOT be forwarded to the PTY
 * — if they are, the remote shell sees them as typed text and echoes garbage
 * like "10;rgb:b0b0/c8c8/e0e0" into the prompt.
 *
 * Covered sequences (xterm.js v5.5.0):
 *   OSC 4/10/11/12  — color query responses (ST-terminated)
 *   DA1 / DA2       — device attribute responses
 *   DSR / CPR       — status & cursor-position reports
 *   DECRQM          — mode report ($y)
 *   Window ops      — size in chars / pixels / cell-size
 *   Focus events    — CSI I / CSI O
 *   DECRQSS         — DCS status-string responses
 *   SGR mouse       — SGR-encoded mouse reports
 */
const XTERM_RESPONSE_RE = new RegExp(
  // OSC color responses: \x1b]10;rgb:xxxx/xxxx/xxxx  (BEL or ST terminated)
  '\\x1b\\](?:1[012]|4;\\d{1,3});rgb:[\\da-f]{4}/[\\da-f]{4}/[\\da-f]{4}(?:\\x1b\\\\|\\x07)' +
  '|' +
  // DA1: \x1b[?1;2c   DA2: \x1b[>0;276;0c
  '\\x1b\\[\\?[\\d;]+c|\\x1b\\[>[\\d;]+c' +
  '|' +
  // DSR status OK: \x1b[0n   CPR: \x1b[row;colR / \x1b[?row;colR
  '\\x1b\\[0n|\\x1b\\[\\??\\d+;\\d+R' +
  '|' +
  // DECRQM: \x1b[?mode;val$y
  '\\x1b\\[\\??\\d+;\\d+\\$y' +
  '|' +
  // Window-ops responses: \x1b[8;rows;colst  \x1b[4;h;wt  \x1b[6;h;wt
  '\\x1b\\[[468];\\d+;\\d+t' +
  '|' +
  // Focus reports: \x1b[I / \x1b[O
  '\\x1b\\[[IO]' +
  '|' +
  // DECRQSS (DCS): \x1bP0$r...\x1b\\  or  \x1bP1$r...\x1b\\
  '\\x1bP[01]\\$r[^\\x1b]*\\x1b\\\\' +
  '|' +
  // SGR mouse reports: \x1b[<btn;col;rowM/m
  '\\x1b\\[<\\d+;\\d+;\\d+[Mm]',
  'g'
)

// How long after a resize to auto-anchor incoming PTY output to the bottom.
// SIGWINCH causes the child process to redraw, and that async output can
// contain cursor-home sequences that clobber the viewport position.
const RESIZE_ANCHOR_MS = 500

export default function Terminal({ sessionId }) {
  const containerRef  = useRef(null)
  const xtermRef      = useRef(null)
  const fitAddonRef   = useRef(null)
  // wsRef always points at the CURRENT live WebSocket.
  // onData reads this ref — no listener rebinding needed on reconnect.
  const wsRef         = useRef(null)
  const retryRef      = useRef(null)
  const retryCountRef = useRef(0)
  const mountedRef    = useRef(true)  // false after unmount
  const resizeTimerRef = useRef(null) // debounce timer for ResizeObserver
  // Timestamp of last resize sent to PTY — used to auto-anchor viewport
  // when async SIGWINCH output arrives shortly after a resize.
  const lastResizeAtRef = useRef(0)
  // Whether the user was at the bottom when the last resize occurred.
  // Only anchor post-resize output if they were — otherwise we'd override
  // their deliberate scroll-up position.
  const wasAtBottomAtResizeRef = useRef(true)

  // sessionIdRef tracks the latest sessionId (may change on rekey from
  // pending-xxx → real UUID) without causing effect re-runs.  The connect
  // callback reads this ref so reconnect URLs always use the current ID.
  const sessionIdRef  = useRef(sessionId)

  const [wsState, setWsState]   = useState('connecting')
  const [exitCode, setExitCode] = useState(null)

  // Keep the ref in sync whenever the prop changes (rekey)
  useEffect(() => { sessionIdRef.current = sessionId }, [sessionId])

  // ── Create xterm once per sessionId ──────────────────────────────────────
  useEffect(() => {
    if (!containerRef.current) return
    mountedRef.current    = true
    retryCountRef.current = 0

    const xterm    = new XTerm({
      theme: XTERM_THEME,
      fontFamily: '"Berkeley Mono", "Cascadia Code", "Fira Code", monospace',
      fontSize: 13,
      lineHeight: 1.4,
      cursorBlink: true,
      cursorStyle: 'bar',
      scrollback: 5000,
      allowProposedApi: true,
    })
    const fitAddon = new FitAddon()
    xterm.loadAddon(fitAddon)
    xterm.loadAddon(new WebLinksAddon())
    xterm.open(containerRef.current)
    // Force a synchronous layout reflow before measuring. Without this,
    // fitAddon.fit() can run before sibling elements (e.g. PromptStrip)
    // have been laid out, calculating rows for a taller container than the
    // terminal actually ends up with. Reading clientHeight is the standard
    // way to flush pending layout — the browser must compute geometry to
    // answer the query.  This ensures fit() sees the final container size.
    void containerRef.current.clientHeight
    safeFit(xterm, fitAddon)

    xtermRef.current    = xterm
    fitAddonRef.current = fitAddon

    // Smart Ctrl+C — mirrors WSL terminal behaviour:
    //   Ctrl+C with selection → copy to clipboard, swallow the keypress
    //   Ctrl+C without selection → pass \x03 (SIGINT) through to PTY
    // Paste (Ctrl+V) is handled natively by xterm's hidden textarea —
    // pasted text flows through onData like normal keyboard input.
    xterm.attachCustomKeyEventHandler((e) => {
      if (e.type !== 'keydown') return true

      if (e.ctrlKey && e.key === 'c') {
        const sel = xterm.getSelection()
        if (sel) {
          navigator.clipboard.writeText(sel).catch(() => {})
          xterm.clearSelection()
          return false  // swallow — don't send \x03 to PTY
        }
        return true  // no selection — let SIGINT through normally
      }

      return true
    })

    // Register onData ONCE. It writes to wsRef.current so it always uses
    // the live socket without ever being re-registered.
    // Programmatic xterm.js responses (OSC color queries, DA, DSR, etc.)
    // are stripped — they are NOT user input and must not reach the PTY.
    xterm.onData(data => {
      const cleaned = data.replace(XTERM_RESPONSE_RE, '')
      if (!cleaned) return  // pure programmatic response — nothing to forward
      const ws = wsRef.current
      if (ws?.readyState === WebSocket.OPEN) {
        ws.send(JSON.stringify({ type: 'input', data: cleaned }))
      }
    })

    // Resize observer — trailing-edge debounce.
    //
    // During a window drag the observer fires every animation frame (~16ms).
    // We collapse the entire cascade into ONE fit + ONE PTY resize message by
    // waiting until no resize events have fired for 150ms.  This is long
    // enough to absorb the sidebar CSS transition (150ms ease) too, so the
    // terminal only reflows once after the animation finishes.
    const RESIZE_DEBOUNCE_MS = 150
    const observer = new ResizeObserver(() => {
      clearTimeout(resizeTimerRef.current)
      resizeTimerRef.current = setTimeout(() => {
        if (!fitAddonRef.current || !xtermRef.current) return
        const prevCols = xtermRef.current.cols
        const prevRows = xtermRef.current.rows
        // Capture scroll state before fit() changes it — used by the
        // post-resize output anchor to decide whether to re-anchor.
        const buf = xtermRef.current.buffer.active
        wasAtBottomAtResizeRef.current = (buf.viewportY >= buf.baseY)
        safeFit(xtermRef.current, fitAddonRef.current)
        // Only notify the PTY if the grid actually changed dimensions
        if (xtermRef.current.cols === prevCols && xtermRef.current.rows === prevRows) return
        lastResizeAtRef.current = Date.now()
        const ws = wsRef.current
        if (ws?.readyState === WebSocket.OPEN) {
          ws.send(JSON.stringify({
            type: 'resize',
            cols: xtermRef.current.cols,
            rows: xtermRef.current.rows,
          }))
        }
      }, RESIZE_DEBOUNCE_MS)
    })
    observer.observe(containerRef.current)

    return () => {
      mountedRef.current = false
      clearTimeout(retryRef.current)
      clearTimeout(resizeTimerRef.current)
      observer.disconnect()
      // Close socket cleanly — onclose will fire but mountedRef guards the retry
      wsRef.current?.close()
      wsRef.current = null
      xterm.dispose()
      xtermRef.current    = null
      fitAddonRef.current = null
    }
  }, [sessionId]) // full remount on session switch — guaranteed by key={sessionId} in App

  // ── WebSocket connect / auto-reconnect ───────────────────────────────────
  const connect = useCallback(() => {
    if (!mountedRef.current) return
    const xterm    = xtermRef.current
    const fitAddon = fitAddonRef.current
    if (!xterm || !fitAddon) return

    setWsState('connecting')

    // Read the LATEST sessionId from the ref (may have changed via rekey)
    // rather than capturing it in the closure. This ensures reconnect URLs
    // point at the real session ID after a pending → real transition.
    const currentId = sessionIdRef.current
    const params = new URLSearchParams({
      cols: String(xterm.cols),
      rows: String(xterm.rows),
    })
    const ws = new WebSocket(`${WS_BASE}/ws/terminal/${currentId}?${params}`)
    wsRef.current = ws  // point the ref at the new socket immediately

    ws.onopen = () => {
      if (!mountedRef.current) { ws.close(); return }
      retryCountRef.current = 0
      setWsState('open')
      setExitCode(null)
      // Sync PTY to actual terminal dimensions immediately on connect.
      // The initial cols/rows are sent as query params in the WS URL, but
      // if the PTY already existed (e.g. reconnect, second tab) the server
      // resize only happens inside spawnPty — this explicit message covers
      // any race where the container resized between URL construction and
      // the socket actually opening.
      ws.send(JSON.stringify({
        type: 'resize',
        cols: xterm.cols,
        rows: xterm.rows,
      }))
      xterm.focus()
    }

    ws.onmessage = ({ data: raw }) => {
      try {
        const msg = JSON.parse(raw)
        if (msg.type === 'output') {
          // After a resize, the PTY child redraws via SIGWINCH. That async
          // output can contain cursor-home escape sequences that yank the
          // viewport to the top.  Re-anchor to the bottom during the settle
          // window — but only if the user was already at the bottom when the
          // resize occurred (don't override a deliberate scroll-up).
          //
          // The anchor is passed as a write() callback so it runs AFTER
          // xterm's async WriteBuffer parses the data — calling scrollToBottom
          // synchronously after write() would race against the internal parser.
          const shouldAnchor = wasAtBottomAtResizeRef.current
            && (Date.now() - lastResizeAtRef.current < RESIZE_ANCHOR_MS)
          xterm.write(msg.data, shouldAnchor ? () => xterm.scrollToBottom() : undefined)
        }
        if (msg.type === 'exit')   { setExitCode(msg.exitCode); setWsState('exited') }
      } catch {
        xterm.write(raw)
      }
    }

    ws.onclose = () => {
      if (!mountedRef.current) return
      // wsRef might already point at a newer socket if we reconnected quickly
      if (wsRef.current !== ws) return

      const delay = RECONNECT_DELAYS[Math.min(retryCountRef.current, RECONNECT_DELAYS.length - 1)]
      retryCountRef.current++
      setWsState('reconnecting')
      xterm.writeln(`\r\n\x1b[33m[connection lost — retrying in ${delay / 1000}s]\x1b[0m`)

      retryRef.current = setTimeout(() => {
        if (mountedRef.current) connect()
      }, delay)
    }

    ws.onerror = () => { /* onclose always follows — handled there */ }
  }, []) // no sessionId dep — reads from sessionIdRef

  // Start connection after xterm is mounted (next tick)
  useEffect(() => {
    const t = setTimeout(connect, 0)
    return () => clearTimeout(t)
  }, [connect])

  const manualReconnect = () => {
    clearTimeout(retryRef.current)
    retryCountRef.current = 0
    setWsState('connecting')
    const old = wsRef.current
    wsRef.current = null
    old?.close()
    setTimeout(connect, 50)
  }

  return (
    <div className="terminal-wrap">
      {wsState === 'connecting' && (
        <div className="terminal-loading">
          <div className="spinner" />
          Connecting to agent…
        </div>
      )}

      <div
        ref={containerRef}
        style={{ width: '100%', height: '100%', visibility: wsState === 'connecting' ? 'hidden' : 'visible' }}
      />

      {(wsState === 'reconnecting' || wsState === 'exited') && (
        <div className="terminal-overlay-badge">
          {wsState === 'exited'
            ? `Process exited (code ${exitCode ?? '?'})`
            : 'Connection lost — retrying…'
          }
          <button
            className="btn btn-primary"
            style={{ padding: '3px 10px', fontSize: '10px', marginLeft: '8px' }}
            onClick={manualReconnect}
          >
            Reconnect now
          </button>
        </div>
      )}
    </div>
  )
}
